const aliens = [
    {
        id: 1,
        name: "Heatblast",
        species: "Pyronite",
        planet: "Pyros",
        series: "Classic",
        image_url: "whats-your-favorite-heatblast-design-v0-k9tvlwvpxgo81.webp",
        powers: ["Pyrokinesis", "Heat Generation", "Flight (via fire)"],
        weaknesses: ["Water", "Fire Extinguishers"],
        description: ">> PLUMBER DATABASE ENTRY: 001\nSUBJECT: PYRONITE\n\nA humanoid entity composed entirely of living magma. Pyronites are capable of projecting intense solar-grade fire and manipulating volcanic energies. Their internal core temperature can exceed 5000 degrees Celsius, allowing them to melt through specialized alloy containers with ease.",
        unlock_status: "ACTIVE"
    },
    {
        id: 2,
        name: "Wildmutt",
        species: "Vulpimancer",
        planet: "Vulpin",
        series: "Classic",
        image_url: "Wildmutt_OS_Omnitrix_side.webp",
        powers: ["Enhanced Senses", "Agility", "Sharp Claws"],
        weaknesses: ["Loud Noises", "Strong Smells"],
        description: ">> PLUMBER DATABASE ENTRY: 002\nSUBJECT: VULPIMANCER\n\nHailing from the pitch-black planet of Vulpin, this species lacks optical organs. They compensate with highly sensitive gill-like nostrils on their neck, granting them a form of 'thermal vision' via scent. Their agility is unmatched in dense forest environments.",
        unlock_status: "ACTIVE"
    },
    {
        id: 3,
        name: "Diamondhead",
        species: "Petrosapien",
        planet: "Petropia",
        series: "Classic",
        image_url: "Diamondhead_oficial.webp",
        powers: ["Crystallokinesis", "Superhuman Durability", "Weapon Shapeshifting"],
        weaknesses: ["Sonic Vibrations"],
        description: ">> PLUMBER DATABASE ENTRY: 003\nSUBJECT: PETROSAPIEN\n\nComposed of an organic, ultra-dense crystalline structure. Petrosapiens can manipulate their molecular density to grow crystal shards from their body or reshape limbs into weaponry. Their skin is virtually invulnerable to most physical and energy-based projectiles.",
        unlock_status: "ACTIVE"
    },
    {
        id: 4,
        name: "XLR8",
        species: "Kineceleran",
        planet: "Kinet",
        series: "Classic",
        image_url: "XLR8.webp",
        powers: ["Super Speed", "Enhanced Reflexes", "Vortex Creation"],
        weaknesses: ["Magnets", "Slippery Surfaces"],
        description: ">> PLUMBER DATABASE ENTRY: 004\nSUBJECT: KINECELERAN\n\nEquipped with specialized friction-reducing orbs on their feet, Kinecelerans can reach speeds exceeding 500 MPH in seconds. Their accelerated metabolism allows for lightning-fast reflexes, making them invisible to the naked human eye during peak velocity.",
        unlock_status: "ACTIVE"
    },
    {
        id: 5,
        name: "Grey Matter",
        species: "Galvan",
        planet: "Galvan Prime",
        series: "Classic",
        image_url: "Grey_Matter.webp",
        powers: ["Super Intelligence", "Small Size", "Wall Climbing"],
        weaknesses: ["Physical Weakness"],
        description: ">> PLUMBER DATABASE ENTRY: 005\nSUBJECT: GALVAN\n\nSmall in stature but possessing the highest IQ in the known galaxy. Galvans are the architects of the most advanced technology in the universe, including the Omnitrix itself. Their dual-brain system allows them to process complex data streams simultaneously.",
        unlock_status: "ACTIVE"
    },
    {
        id: 6,
        name: "Four Arms",
        species: "Tetramand",
        planet: "Khoros",
        series: "Classic",
        image_url: "Four_arms_os_render.webp",
        powers: ["Superhuman Strength", "Enhanced Durability", "High Leaps"],
        weaknesses: ["Size (tight spaces)", "Small agile opponents"],
        description: ">> PLUMBER DATABASE ENTRY: 006\nSUBJECT: TETRAMAND\n\nA warrior species from the desert world of Khoros. Tetramands possess four highly muscular arms and two pairs of eyes. Their strength allows them to lift objects several times their own mass and generate shockwaves simply by clapping their hands together.",
        unlock_status: "ACTIVE"
    },
    {
        id: 7,
        name: "Stinkfly",
        species: "Lepidopterran",
        planet: "Lepidopterra",
        series: "Classic",
        image_url: "imgbin-stinkfly-ben-10-concept-art-cannonbolt-stinkfly-021xqVK9nksx1nWWHHP78V5Uw_t-removebg-preview.png",
        powers: ["Flight", "Slime Projection", "Sharp Tail"],
        weaknesses: ["Water (on wings)", "Fire"],
        description: ">> PLUMBER DATABASE ENTRY: 007\nSUBJECT: LEPIDOPTERRAN\n\nAn insectoid species with 360-degree vision thanks to their four eye-stalks. They secrete a highly flammable and adhesive slime from their eyes and mouth, which they use to immobilize targets. Their wings allow for incredible aerial maneuverability.",
        unlock_status: "ACTIVE"
    },
    {
        id: 8,
        name: "Ripjaws",
        species: "Piscciss Volann",
        planet: "Piscciss",
        series: "Classic",
        image_url: "ripjaws-removebg-preview.png",
        powers: ["Underwater Breathing", "Powerful Jaws", "Enhanced Swimming"],
        weaknesses: ["Dehydration"],
        description: ">> PLUMBER DATABASE ENTRY: 008\nSUBJECT: PISCCISS VOLANN\n\nEvolutionary apex predators from the water-world of Piscciss. They possess a lure-light on their head for dark trenches and jaws powerful enough to bite through solid steel. However, they require constant hydration and will weaken rapidly in dry environments.",
        unlock_status: "ACTIVE"
    },
    {
        id: 9,
        name: "Upgrade",
        species: "Galvanic Mechamorph",
        planet: "Galvan B",
        series: "Classic",
        image_url: "if-upgrade-is-a-being-made-of-completely-of-nano-machines-v0-zcoa58ugzqlc1 Background Removed.png",
        powers: ["Technopathy", "Technological Mimicry", "Energy Blasts"],
        weaknesses: ["Electricity", "Magnets"],
        description: ">> PLUMBER DATABASE ENTRY: 009\nSUBJECT: GALVANIC MECHAMORPH\n\nAn accidental creation of the Galvans, these techno-organic beings are composed of billions of nanites. They can merge with any mechanical device, 'upgrading' it far beyond its original design. They can also reform their bodies to mimic technology they have previously interfaced with.",
        unlock_status: "ACTIVE"
    },
    {
        id: 10,
        name: "Ghostfreak",
        species: "Ectonurite",
        planet: "Anur Phaetos",
        series: "Classic",
        image_url: "GhostfreakPose2.webp",
        powers: ["Intangibility", "Invisibility", "Possession"],
        weaknesses: ["Sunlight", "Magic"],
        description: ">> PLUMBER DATABASE ENTRY: 010\nSUBJECT: ECTONURITE\n\nTerrifying phantoms from the Anur System. Ectonurites lack a traditional nervous system and are capable of phasing through solid matter by shifting their molecular frequency. Their true form is hidden beneath a protective layer of skin to shield them from lethal UV radiation.",
        unlock_status: "ACTIVE"
    },
    {
        id: 11,
        name: "LOCKED DNA",
        species: "UNKNOWN",
        planet: "UNKNOWN",
        series: "???",
        image_url: "",
        powers: [],
        weaknesses: [],
        description: "DNA SEQUENCE ENCRYPTED. CLICK TO DECRYPT A RANDOM DNA STREAM FROM THE DATABASE.",
        unlock_status: "LOCKED"
    }
];

const database = {
    aliens: [
        { name: "Way Big", species: "To'kustar", planet: "Cosmic Storms", series: "Classic", image_url: "https://static.wikia.nocookie.net/ben10/images/6/65/Way_Big_UA.png", powers: ["Cosmic Rays", "Super Strength", "Size"], weaknesses: ["Fin vulnerability"], description: "Massive cosmic giants born from cosmic storms. They are among the rarest and most powerful beings in the galaxy, capable of firing cosmic rays with enough power to destroy planets." },
        { name: "Cannonbolt", species: "Arburian Pelarota", planet: "Arburia", series: "Classic", image_url: "https://static.wikia.nocookie.net/ben10/images/0/03/Cannonbolt_OS_Render.png", powers: ["Sphere Transformation", "Super Speed (rolling)", "Durability"], weaknesses: ["Balance", "Frictionless surfaces"], description: "A resilient species that can curl into a near-invulnerable sphere. Once in motion, their kinetic energy is immense, allowing them to shatter obstacles upon impact." },
        { name: "Wildvine", species: "Florauna", planet: "Flors Verdance", series: "Classic", image_url: "https://static.wikia.nocookie.net/ben10/images/0/05/Wildvine_OS_Render.png", powers: ["Elasticity", "Plant Merging", "Explosive Seeds"], weaknesses: ["Fire", "Lack of sunlight"], description: "Sentient plant-life capable of growing thorns and explosive seeds. Their limbs can stretch for hundreds of feet, and they can communicate with other flora to manipulate the environment." },
        { name: "Upchuck", species: "Gourmand", planet: "Peptos XII", series: "Classic", image_url: "https://static.wikia.nocookie.net/ben10/images/6/6b/Upchuck_OS_Render.png", powers: ["Solid Matter Ingestion", "Energy Spit", "Prehensile Tongues"], weaknesses: ["Standard Food"], description: "Gourmands possess an 'extra-dimensional' stomach that can digest any inorganic matter. They can then expel the converted energy as high-explosive bio-organic blasts." },
        { name: "Echo Echo", species: "Sonorosian", planet: "Sonorosia", series: "Alien Force", image_url: "https://static.wikia.nocookie.net/ben10/images/7/7a/Echo_Echo_uaf_render.png", powers: ["Self-Duplication", "Sonic Screams", "Echolocation"], weaknesses: ["Physical fragility"], description: "Small silicon-based beings that are essentially living sound waves trapped in a containment suit. They can duplicate themselves indefinitely and generate wall-shattering sonic frequencies." },
        { name: "Humungousaur", species: "Vaxasaurian", planet: "Terradino", series: "Alien Force", image_url: "Humungousaur_UAF_Model.webp", powers: ["Superhuman Strength", "Size Alteration", "Durability"], weaknesses: ["Speed", "Electricity"], description: "Powerful saurian warriors with the unique ability to increase their size and density at will. As they grow, their strength increases exponentially, though their speed decreases." },
        { name: "Jetray", species: "Aerophibian", planet: "Aeropela", series: "Alien Force", image_url: "https://static.wikia.nocookie.net/ben10/images/2/2b/Jetray_UAF_Model.png", powers: ["Flight", "Neuroshock Blasts", "Super Speed"], weaknesses: ["Durability"], description: "Highly adapted for both supersonic flight and high-pressure underwater environments. They can fire neuroshock energy from their eyes and tail to paralyze nervous systems." },
        { name: "Big Chill", species: "Necrofriggian", planet: "Kylmyys", series: "Alien Force", image_url: "Ultimate_Big_Chill_Uncloaked_Shaded.webp", powers: ["Cryokinesis", "Intangibility", "Flight"], weaknesses: ["Fire", "Energy Absorption"], description: "Ghostly moth-like aliens that can lower their body temperature to absolute zero. They can phase through solid matter and freeze the air around them instantly." },
        { name: "Chromastone", species: "Crystalsapien", planet: "Petropia", series: "Alien Force", image_url: "https://static.wikia.nocookie.net/ben10/images/4/4c/Chromastone_UAF_Model.png", powers: ["Energy Absorption", "Energy Redirection", "Durability"], weaknesses: ["Physical impact"], description: "The living conductor of the Petrosapien race. Crystalsapiens can absorb almost any form of energy and channel it into powerful multi-spectrum laser beams." },
        { name: "Brainstorm", species: "Cerebrocrustacean", planet: "Encephalonus IV", series: "Alien Force", image_url: "https://static.wikia.nocookie.net/ben10/images/6/6a/Brainstorm_UAF_Model.png", powers: ["Super Intelligence", "Electrokinesis", "Force Fields"], weaknesses: ["Arrogance", "Standard water"], description: "Massive crab-like entities with biological CPUs located in their skulls. They can calculate thousands of battle outcomes in seconds and unleash bio-electrical storms." },
        { name: "Spidermonkey", species: "Arachnichimp", planet: "Aranhascimmia", series: "Alien Force", image_url: "https://static.wikia.nocookie.net/ben10/images/8/87/Spidermonkey_UAF_Model.png", powers: ["Web Projection", "Enhanced Agility", "Wall Climbing"], weaknesses: ["Web tangling"], description: "Agile forest-dwellers with four arms and spider-like traits. They can spin webs from their tails stronger than steel and possess incredible acrobatic reflexes." },
        { name: "Goop", species: "Polymorph", planet: "Viscosia", series: "Alien Force", image_url: "https://static.wikia.nocookie.net/ben10/images/3/30/Goop_UAF_Model.png", powers: ["Shapeshifting", "Acidity", "Regeneration"], weaknesses: ["Anti-gravity projector dependency"], description: "A sentient blob of protoplasmic slime. They can reshape their form at will and secrete highly corrosive acids to dissolve any obstacle." },
        { name: "Alien X", species: "Celestialsapien", planet: "Forge of Creation", series: "Alien Force", image_url: "https://static.wikia.nocookie.net/ben10/images/c/c9/Alien_X_UAF_Model.png", powers: ["Omnipotence", "Reality Warping", "Time Manipulation"], weaknesses: ["Indecisive personalities"], description: "God-like beings that reside outside of time. They have the power to warp reality with a mere thought, though they are often paralyzed by internal debate." },
        { name: "Lodestar", species: "Biosovortian", planet: "Maxwell", series: "Alien Force", image_url: "https://static.wikia.nocookie.net/ben10/images/0/05/Lodestar_UAF_Model.png", powers: ["Magnetokinesis", "Levitation", "Regeneration"], weaknesses: ["Non-magnetic materials"], description: "Creatures with magnetized skeletal structures. They can manipulate magnetic fields to fly, throw metal objects, or even regenerate their bodies if shattered." },
        { name: "Rath", species: "Appoplexian", planet: "Appoplexia", series: "Alien Force", image_url: "https://static.wikia.nocookie.net/ben10/images/3/3b/Rath_UAF_Model.png", powers: ["Superhuman Strength", "Claws", "Durability"], weaknesses: ["Rage", "Hydrophobia"], description: "Aggressive feline warriors known for their short tempers. They possess large retractable claws and skin tough enough to survive most conventional weaponry." },
        { name: "Nanomech", species: "Nanochip", planet: "Earth", series: "Alien Force", image_url: "https://static.wikia.nocookie.net/ben10/images/c/cc/Nanomech_UAF_Model.png", powers: ["Size Alteration", "Flight", "Bio-electricity"], weaknesses: ["Physical vulnerability"], description: "A unique hybrid of human DNA and alien nano-technology. They can shrink to sub-atomic sizes and fire bio-electrical energy from their composite body." },
        { name: "Water Hazard", species: "Orishan", planet: "Kiusana", series: "Ultimate Alien", image_url: "https://static.wikia.nocookie.net/ben10/images/4/4b/Water_Hazard_UA.png", powers: ["Hydrokinesis", "Exoskeleton", "Moisture Absorption"], weaknesses: ["Electricity"], description: "Armored cephalopods that can absorb moisture from the air and expel it as high-pressure water jets through specialized ports in their hands." },
        { name: "Ampfibian", species: "Amperi", planet: "Andromeda", series: "Ultimate Alien", image_url: "https://static.wikia.nocookie.net/ben10/images/b/b5/Ampfibian_UA.png", powers: ["Electrokinesis", "Intangibility", "Telepathy"], weaknesses: ["Conductors"], description: "Jellyfish-like aliens that can travel through electrical currents. They possess the ability to read the electrical pulses of a target's nervous system." },
        { name: "Armodrillo", species: "Talpaedan", planet: "Terraexcava", series: "Ultimate Alien", image_url: "https://static.wikia.nocookie.net/ben10/images/4/47/Armodrillo_UA.png", powers: ["Terrakinesis", "Jackhammer Arms", "Burrowing"], weaknesses: ["Soft ground"], description: "Living excavation machines. Their jackhammer-like limbs can trigger localized earthquakes or burrow through solid bedrock in minutes." },
        { name: "Terraspin", species: "Geochelone Aerio", planet: "Aldabra", series: "Ultimate Alien", image_url: "https://static.wikia.nocookie.net/ben10/images/e/ea/Terraspin_UA.png", powers: ["Aerokinesis", "Flight", "Magic Immunity"], weaknesses: ["Slow movement"], description: "Peaceful turtle-like philosophers whose internal organs function as powerful turbines. They can rotate their flippers to create hurricane-force winds." },
        { name: "NRG", species: "Prypiatosian-B", planet: "Prypiatos", series: "Ultimate Alien", image_url: "https://static.wikia.nocookie.net/ben10/images/b/bd/NRG_UA.png", powers: ["Radiokinesis", "Heat Generation", "Durability"], weaknesses: ["Lead containment"], description: "Living nuclear reactors contained within a specialized Plumber-grade lead suit. Without their suit, their radiation levels are lethal to all nearby organic life." },
        { name: "Fasttrack", species: "Citrakayah", planet: "Chalybeas", series: "Ultimate Alien", image_url: "https://static.wikia.nocookie.net/ben10/images/a/a2/Fasttrack_UA.png", powers: ["Super Speed", "Enhanced Agility", "Superhuman Strength"], weaknesses: ["Slippery surfaces"], description: "A high-speed feline species that combines velocity with physical strength. They are more durable than Kinecelerans but slightly slower." },
        { name: "ChamAlien", species: "Merlinisapien", planet: "Camoflage", series: "Ultimate Alien", image_url: "https://static.wikia.nocookie.net/ben10/images/9/93/ChamAlien_UA.png", powers: ["Camouflage", "Agility", "Sharp Stinger"], weaknesses: ["Shadows"], description: "The masters of stealth. Their skin can perfectly mimic any background, making them invisible to both thermal and infrared detection systems." },
        { name: "Eatle", species: "Oryctini", planet: "Coleop Terra", series: "Ultimate Alien", image_url: "https://static.wikia.nocookie.net/ben10/images/c/c9/Eatle_UA.png", powers: ["Matter Ingestion", "Energy Beams", "Horn Attack"], weaknesses: ["Slow speed"], description: "Rhinoceros beetle-like aliens that consume solid materials to charge their internal energy core. This energy can then be fired as a powerful beam from their horn." },
        { name: "Jury Rigg", species: "Planchaküle", planet: "Aul-Turrhen", series: "Ultimate Alien", image_url: "https://static.wikia.nocookie.net/ben10/images/4/4a/Jury_Rigg_UA.png", powers: ["Technological Intuition", "Speed Building", "Small Size"], weaknesses: ["Destructive tendencies"], description: "Mischievous imps with an instinctive understanding of machinery. They can build a high-tech weapon out of scrap metal in under ten seconds." },
        { name: "Clockwork", species: "Chronosapien", planet: "Chronia", series: "Ultimate Alien", image_url: "https://static.wikia.nocookie.net/ben10/images/9/91/Clockwork_UA.png", powers: ["Chronokinesis", "Time Rays", "Retro-cognition"], weaknesses: ["Physical fragility"], description: "Mechanical beings capable of seeing through time. They can fire rays that age objects into dust or slow down the flow of time for everyone except themselves." },
        { name: "Shocksquatch", species: "Gimlinopithecus", planet: "Pattersonea", series: "Omniverse", image_url: "https://static.wikia.nocookie.net/ben10/images/9/9a/Shocksquatch_OV.png", powers: ["Electrokinesis", "Superhuman Strength", "Durability"], weaknesses: ["Insulation"], description: "Massive electric yeti-like warriors. They generate electrical current through friction as they move and can unleash it in devastating close-quarters strikes." },
        { name: "Bloxx", species: "Segmentasapien", planet: "Polyominus", series: "Omniverse", image_url: "https://static.wikia.nocookie.net/ben10/images/3/3a/Bloxx_OV.png", powers: ["Shapeshifting", "Regeneration", "Structural Modification"], weaknesses: ["Fragility"], description: "Sentient block-like creatures that can rebuild their body into walls, cages, or catapults. They are virtually impossible to permanently damage as long as one block remains." },
        { name: "Gravattack", species: "Galilean", planet: "Keplorr", series: "Omniverse", image_url: "https://static.wikia.nocookie.net/ben10/images/5/52/Gravattack_OV.png", powers: ["Gyrokinesis", "Orbital Fields", "Gravity Reduction"], weaknesses: ["Weight"], description: "Living planetoids with core temperatures high enough to melt steel. They control the fundamental force of gravity, allowing them to orbit objects around their body." },
        { name: "Crashhopper", species: "Orthopterran", planet: "Xylos", series: "Omniverse", image_url: "https://static.wikia.nocookie.net/ben10/images/5/51/Crashhopper_OV.png", powers: ["Super Leaping", "Hardened Head", "Agility"], weaknesses: ["Sticky surfaces"], description: "Insectoid jumpers with hardened chitinous shells. Their leaps can reach heights of over 200 feet, allowing them to drop onto enemies with the force of a meteor." },
        { name: "Ball Weevil", species: "Insectoid", planet: "Curculion", series: "Omniverse", image_url: "https://static.wikia.nocookie.net/ben10/images/2/23/Ball_Weevil_OV.png", powers: ["Plasma Spit", "Adhesive Surface", "Explosion Manipulation"], weaknesses: ["Small size"], description: "Small beetle-like aliens that roll sticky plasma balls. The larger the ball grows, the more explosive damage it deals upon detonation." },
        { name: "Walkatrout", species: "Ickthyperambuloid", planet: "Gilli-Perambulus", series: "Omniverse", image_url: "https://static.wikia.nocookie.net/ben10/images/e/ed/Walkatrout_OV.png", powers: ["Slippery Skin", "Underwater Breathing", "Agility"], weaknesses: ["No offensive powers"], description: "A fish-like species that is literally impossible to hold. Their skin secretes a biological oil that renders them immune to all grappling techniques." },
        { name: "Pesky Dust", species: "Nemuina", planet: "Nemunina", series: "Omniverse", image_url: "https://static.wikia.nocookie.net/ben10/images/0/0a/Pesky_Dust_OV.png", powers: ["Sleep Dust", "Dream Manipulation", "Flight"], weaknesses: ["Physical Weakness"], description: "Fairy-like entities that inhabit the dream realm. They use sleep dust to knock out opponents and extract information directly from their subconscious mind." },
        { name: "The Worst", species: "Atrocian", planet: "Atrocius 0", series: "Omniverse", image_url: "https://static.wikia.nocookie.net/ben10/images/4/4e/The_Worst_OV.png", powers: ["Invulnerability", "Pain Tolerance", "Small Size"], weaknesses: ["Lack of offensive abilities"], description: "Despite their appearance, Atrocians are the most durable beings in the galaxy. They can survive being crushed by a star, though they will complain about it loudly." },
        { name: "Kickin Hawk", species: "Liamin", planet: "Liamina", series: "Omniverse", image_url: "https://static.wikia.nocookie.net/ben10/images/6/67/Kickin_Hawk_OV.png", powers: ["Combat Skills", "Superhuman Strength", "Agility"], weaknesses: ["Leg injuries"], description: "Expert hand-to-hand combatants with incredibly powerful leg muscles. Their talons are sharp enough to slice through Kevlar during mid-air strikes." },
        { name: "Toepick", species: "Fearean", planet: "Anur Phateos", series: "Omniverse", image_url: "https://static.wikia.nocookie.net/ben10/images/c/c5/Toepick_OV.png", powers: ["Fear Inducement", "Hulking Strength", "Helmet Armor"], weaknesses: ["Blind opponents"], description: "A species so terrifying that their face is a biological weapon of mass psychological destruction. Looking at them causes immediate and permanent catatonic fear." },
        { name: "Astrodactyl", species: "Pterosapien", planet: "Terradino", series: "Omniverse", image_url: "https://static.wikia.nocookie.net/ben10/images/a/a2/Astrodactyl_OV.png", powers: ["Energy Whips", "Propulsion Flight", "Stellar Breams"], weaknesses: ["Wing damage"], description: "Saurian pilots equipped with internal jet propulsion systems. They generate energy whips from their forearms for mid-air grappling and combat." },
        { name: "Bullfrag", species: "Incursean", planet: "Incursia", series: "Omniverse", image_url: "https://static.wikia.nocookie.net/ben10/images/5/5f/Bullfrag_OV.png", powers: ["Enhanced Agility", "Prehensile Tongue", "Superhuman Jump"], weaknesses: ["Standard frog weaknesses"], description: "The apex evolution of the Incursean warmongers. They combine superhuman strength with a tongue that can strike with the force of a cannonball." },
        { name: "Atomix", species: "Unknown", planet: "Unknown", series: "Omniverse", image_url: "https://static.wikia.nocookie.net/ben10/images/4/4b/Atomix_OV.png", powers: ["Nuclear Generation", "Energy Blasts", "Flight"], weaknesses: ["Energy Depletion"], description: "A high-tech walking nuclear reactor. Atomix is second only to Alien X in raw power, capable of creating miniature suns to incinerate his enemies." },
        { name: "Gutrot", species: "Unknown", planet: "Unknown", series: "Omniverse", image_url: "https://static.wikia.nocookie.net/ben10/images/2/23/Gutrot_OV.png", powers: ["Gas Manipulation", "Chemical Creation", "Intelligence"], weaknesses: ["Gas masks"], description: "A biological chemistry lab. Gutrot can synthesize any chemical compound or gas within his transparent body and expel it to neutralize entire armies." },
        { name: "Whampire", species: "Vladat", planet: "Anur Vladias", series: "Omniverse", image_url: "https://static.wikia.nocookie.net/ben10/images/8/85/Whampire_OV.png", powers: ["Hypnosis", "Life Force Draining", "Flight"], weaknesses: ["Sunlight"], description: "Predators of the Anur system. They use Corrupturas to mind-control their prey and can transform into small bat-like entities for infiltration." },
        { name: "Feedback", species: "Conductoid", planet: "Teslavorr", series: "Omniverse", image_url: "Teen_Feedback_Stand.webp", powers: ["Energy Absorption", "Energy Redirection", "Agility"], weaknesses: ["Lack of energy to absorb"], description: "Living energy conductors with tentacles that act as power plugs. They can absorb infinite amounts of energy and fire it back with concentrated force." }
    ],
    characters: [
        { name: "Ben Tennyson", description: "The legendary wielder of the Omnitrix. Over 10 years of service, Benjamin Tennyson has saved the universe more times than Plumber records can accurately track.", role: "Hero", species: "Human", planet: "Earth", image_url: "https://static.wikia.nocookie.net/ben10/images/2/21/Ben_Tennyson_OV_Render.png" },
        { name: "Gwen Tennyson", description: "A master of Anodite magic and mana manipulation. Her intelligence and mystical prowess make her one of the most powerful beings on Earth.", role: "Ally", species: "Human (Anodite)", planet: "Earth", image_url: "https://static.wikia.nocookie.net/ben10/images/1/1a/Gwen_OV_Render.png" },
        { name: "Max Tennyson", description: "Magister of the Plumbers and the greatest mentor in the galaxy. His knowledge of alien technology and strategy is unrivaled.", role: "Mentor", species: "Human", planet: "Earth", image_url: "https://static.wikia.nocookie.net/ben10/images/0/03/Max_Tennyson_OV.png" },
        { name: "Kevin Levin", description: "An Osmosian with the ability to absorb matter and energy. Former criminal turned elite plumber ally, known for his mechanical expertise.", role: "Ally", species: "Human (Osmosian)", planet: "Earth", image_url: "https://static.wikia.nocookie.net/ben10/images/a/a2/Kevin_OV_Render.png" },
        { name: "Rook Blonko", description: "A Revonnahgander Plumber known for his tactical brilliance and mastery of the Proto-Tool. Partner to Ben Tennyson.", role: "Ally", species: "Revonnahgander", planet: "Revonnah", image_url: "https://static.wikia.nocookie.net/ben10/images/a/a6/Rook_Blonko_OV_Render.png" },
        { name: "Vilgax", description: "The Conqueror of Ten Worlds. A Chimera Sui Generis warlord whose obsession with the Omnitrix has fueled a thousand-year war.", role: "Villain", species: "Chimera Sui Generis", planet: "Vilgaxia", image_url: "https://static.wikia.nocookie.net/ben10/images/f/f3/Vilgax_OV_Render.png" },
        { name: "Azmuth", description: "The First Thinker of the Galvans. His intellect is beyond measurement, having created the Omnitrix to promote peace across the stars.", role: "Mentor", species: "Galvan", planet: "Galvan Prime", image_url: "https://static.wikia.nocookie.net/ben10/images/c/c2/Azmuth_OV_Render.png" },
        { name: "Professor Paradox", description: "An eternal time-traveler who exists outside the linear flow of time. He assists the Tennyson family in protecting the multiverse.", role: "Ally", species: "Human", planet: "Earth", image_url: "https://static.wikia.nocookie.net/ben10/images/7/7e/Professor_Paradox_UA_Render.png" },
        { name: "Tetrax Shard", description: "A Petrosapien warrior and bounty hunter who betrayed Vilgax to help Ben. He is a master of crystal combat.", role: "Ally", species: "Petrosapien", planet: "Petropia", image_url: "https://static.wikia.nocookie.net/ben10/images/e/e9/Tetrax_UA_Render.png" },
        { name: "Albedo", description: "Azmuth's former assistant who attempted to copy the Omnitrix. He is now trapped in a human form, fueling his hatred for Ben.", role: "Villain", species: "Galvan", planet: "Galvan Prime", image_url: "https://static.wikia.nocookie.net/ben10/images/b/b3/Albedo_OV_Render.png" }
    ]
};
